FROM apache/airflow:2.8.1-python3.11

# Copy requirements file
COPY requirements.txt /requirements.txt

# Install custom Python packages
RUN pip install --no-cache-dir -r /requirements.txt

# Set the user back to airflow
USER airflow

